post_template = """<post>
<ID></ID>
<Title></Title>
<Content><![CDATA[]]></Content>
<Excerpt></Excerpt>
<Date></Date>
<PostType></PostType>
<Permalink></Permalink>
<ImageURL></ImageURL>
<ImageTitle></ImageTitle>
<ImageCaption></ImageCaption>
<ImageDescription></ImageDescription>
<ImageAltText></ImageAltText>
<ImageFeatured></ImageFeatured>
<AttachmentURL></AttachmentURL>
<Categories></Categories>
<Tags></Tags>
<Status>publish</Status>
<AuthorID></AuthorID>
<AuthorUsername></AuthorUsername>
<AuthorEmail></AuthorEmail>
<AuthorFirstName></AuthorFirstName>
<AuthorLastName></AuthorLastName>
<Slug></Slug>
<Format></Format>
<Template>default</Template>
<Parent>0</Parent>
<ParentSlug>0</ParentSlug>
<Order>0</Order>
<CommentStatus>closed</CommentStatus>
<PingStatus>closed</PingStatus>
<PostModifiedDate></PostModifiedDate>
<_yoast_wpseo_title></_yoast_wpseo_title>
<_yoast_wpseo_metadesc></_yoast_wpseo_metadesc>
<_yoast_wpseo_opengraph-title></_yoast_wpseo_opengraph-title>
<_yoast_wpseo_opengraph-description></_yoast_wpseo_opengraph-description>
<_yoast_wpseo_opengraph-image></_yoast_wpseo_opengraph-image>
</post>"""